# Generated by Django 5.1.3 on 2025-12-09 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='surveys.question'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_selections', to='surveys.answeroption'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveysession'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_answers', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='answeroption',
            index=models.Index(fields=['question', 'order'], name='answer_opti_questio_0d458d_idx'),
        ),
        migrations.AddConstraint(
            model_name='answeroption',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='unique_answer_order_per_question'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['author', 'created_at'], name='surveys_author__1a0277_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['is_active', 'created_at'], name='surveys_is_acti_c66890_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['survey', 'order'], name='questions_survey__d168d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('survey', 'order'), name='unique_question_order_per_survey'),
        ),
        migrations.AddIndex(
            model_name='surveysession',
            index=models.Index(fields=['user', 'survey'], name='survey_sess_user_id_253083_idx'),
        ),
        migrations.AddIndex(
            model_name='surveysession',
            index=models.Index(fields=['survey', 'is_completed'], name='survey_sess_survey__ea1e14_idx'),
        ),
        migrations.AddIndex(
            model_name='surveysession',
            index=models.Index(fields=['user', 'started_at'], name='survey_sess_user_id_fded8a_idx'),
        ),
        migrations.AddIndex(
            model_name='surveysession',
            index=models.Index(fields=['survey', 'completed_at'], name='survey_sess_survey__a87863_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['session', 'question'], name='user_answer_session_b4bcb8_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['survey', 'question'], name='user_answer_survey__e0bf18_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['survey', 'selected_option'], name='user_answer_survey__0553c3_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user', 'survey'], name='user_answer_user_id_95d2ea_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['question', 'selected_option'], name='user_answer_questio_742e0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='useranswer',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_answer_per_question_per_session'),
        ),
    ]
