# Generated by Django 5.1.3 on 2025-12-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeroption',
            options={'ordering': ['question', 'order'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['survey', 'order'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created_at'], 'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterModelOptions(
            name='surveysession',
            options={'ordering': ['-started_at'], 'verbose_name': 'Сессия опроса', 'verbose_name_plural': 'Сессии опросов'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['session', 'question__order'], 'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы пользователей'},
        ),
    ]
